In [1]:
import cv2
import numpy as np

In [2]:
#imread adnd imshow

img_path = 'IMG_2458.jpg'
img = cv2.imread(img_path)
cv2.imshow('image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [3]:
hw = 400
ww = 500

rez_img = cv2.resize(img, (hw, ww))
cv2.imshow('imageezzzz', rez_img)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [4]:
#dimensions (height width) check block2, size?, resize, shape check block2

nh = 500
nw = 500

new_img = cv2.resize(img, (nh, nw))

cv2.imshow('image2', new_img)
cv2.imshow('image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [5]:
#Image matrix its content

image_matrix = np.array(img)
print(image_matrix)

[[[222 138  96]
  [222 138  96]
  [222 138  96]
  ...
  [254 248 241]
  [254 248 241]
  [254 248 241]]

 [[222 138  96]
  [222 138  96]
  [222 138  96]
  ...
  [254 248 241]
  [254 248 241]
  [254 248 241]]

 [[221 137  95]
  [221 137  95]
  [221 137  95]
  ...
  [254 248 241]
  [254 248 241]
  [254 248 241]]

 ...

 [[221  91   0]
  [221  91   2]
  [219  88   1]
  ...
  [204  65   2]
  [202  66   0]
  [203  67   1]]

 [[219  89   0]
  [220  90   1]
  [218  87   0]
  ...
  [204  64   3]
  [201  65   1]
  [202  66   2]]

 [[218  88   0]
  [219  89   0]
  [217  86   0]
  ...
  [204  64   3]
  [201  65   1]
  [202  66   2]]]


In [6]:
#Image shape i.e. height, width, channels

height, width, x = img.shape

print(f"height: {height}, width: {width}")

height: 4032, width: 3024


In [7]:
#Availability of 3 Color Planes

height, width, x = rez_img.shape

temp1 = np.zeros((height, width,x), np.uint8)
temp2 = np.zeros((height, width,x), np.uint8)
temp3 = np.zeros((height, width,x), np.uint8)

temp1[:,:,0] = rez_img[:,:,0]
temp2[:,:,1] = rez_img[:,:,1]
temp3[:,:,2] = rez_img[:,:,2]

cv2.imshow('blue image', temp1)
cv2.imshow('green image', temp2)
cv2.imshow('red image', temp3)

cv2.waitKey(0)
cv2.destroyAllWindows()


In [ ]:
# entirety of task2

img2 = cv2.imread('IMG_2458.jpg')
img3 = cv2.imread('IMG_2458_cpy.jpg')

addimg = cv2.add(img2, img3)
subimg = cv2.subtract(img2, img3)
divimg = cv2.divide(img2, img3)
mulimg = cv2.multiply(img2, img3)

d = []
m = []
z = [0.5, 1, 10, 25, 50]

for i in range(0, 5):
    d.append(cv2.divide(img2, z[i]))
    m.append(cv2.multiply(img2, z[i]))

cv2.imshow('add', addimg)
cv2.imshow('sub', subimg)
cv2.imshow('div', divimg)
cv2.imshow('mul', mulimg)

for i in range(0, 5):
    cv2.imshow(f'div{i}', d[i])
    cv2.imshow(f'mul{i}', m[i])
    cv2.waitKey(0)
    cv2.destroyAllWindows()

cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
import cv2

def convert_to_grayscale_and_save(image_path, output_path):
    # Read the image from the specified file path
    image = cv2.imread(image_path)

    if image is None:
        print("Error: Image not found or invalid file path.")
        return

    # Convert the image to grayscale
    grayscale_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

    # Save the grayscale image as JPG
    cv2.imwrite(output_path, grayscale_image)

if __name__ == "__main__":
    # Replace 'path/to/your/image.jpg' with the actual path to your image file
    image_path = 'IMG_2458.jpg'
    output_path = 'IMG_2458_grey.jpg'

    convert_to_grayscale_and_save(image_path, output_path)