In [2]:
import cv2
import numpy as np

In [9]:
# Replace 'path/to/your/image.jpg' with the actual path to your image file
image_path = 'IMG_2458.jpg'
output_path = 'IMG_2458_grey.jpg'

# Read the image from the specified file path
image = cv2.imread(image_path)

# Convert the image to grayscale
grayscale_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# Save the grayscale image as JPG
cv2.imwrite(output_path, grayscale_image)

True

In [10]:
image = cv2.resize(image, (1000, 1000))
cv2.imshow("rz", image)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [12]:
import cv2
import numpy as np

# Modify at least 10 pixels randomly in the image
num_pixels=10

height, width = image.shape[:2]

mod_img = image

for _ in range(num_pixels):
    # Generate random coordinates (row, column)
    row = np.random.randint(0, height)
    col = np.random.randint(0, width)

    # Generate a random intensity value (0 to 255)
    intensity = np.random.randint(0, 256)

    # Modify the pixel at the random position with the random intensity
    mod_img[row, col] = intensity
    # Wait for a key press and then close the windows


cv2.imshow("Original Image", image)
cv2.imshow("Modified Image", mod_img)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [13]:
block = image[row-1:row+2, col-1:col+2]
print(block)
# Print the coordinates and intensity values of the modified pixel and its neighbors
print(f"Modified Pixel: ({row}, {col}), Intensity: {intensity}")
print("4-Connectivity Neighbors:")
print("Top:      ", block[0, 1])
print("Bottom:   ", block[2, 1])
print("Left:     ", block[1, 0])
print("Right:    ", block[1, 2])

print("8-Connectivity Neighbors:")
print("Top-Left:     ", block[0, 0])
print("Top-Right:    ", block[0, 2])
print("Bottom-Left:  ", block[2, 0])
print("Bottom-Right: ", block[2, 2])
print("-" * 20)

[[[118  89  75]
  [119  90  76]
  [121  92  78]]

 [[118  89  75]
  [230 230 230]
  [120  91  77]]

 [[120  91  77]
  [121  92  78]
  [122  93  79]]]
Modified Pixel: (578, 762), Intensity: 230
4-Connectivity Neighbors:
Top:       [119  90  76]
Bottom:    [121  92  78]
Left:      [118  89  75]
Right:     [120  91  77]
8-Connectivity Neighbors:
Top-Left:      [118  89  75]
Top-Right:     [121  92  78]
Bottom-Left:   [120  91  77]
Bottom-Right:  [122  93  79]
--------------------


In [7]:
cv2.imshow(, 'IMG_2458_cpy.jpg', cv2.COLOR_BGR2GRAY)
cv2.imshow('IMG_2458.jpg', cv2.COLOR_BGR2GRAY)
cv2.waitKey(0)
cv2.destroyAllWindows()

error: OpenCV(4.7.0) :-1: error: (-5:Bad argument) in function 'imshow'
> Overload resolution failed:
>  - Can't convert object to 'str' for 'winname'
>  - Can't convert object to 'str' for 'winname'
>  - Can't convert object to 'str' for 'winname'
